services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/ktor_tutorial_db
      DB_USER: postgres
      DB_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./docker:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: ktor_tutorial_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
volumes:
  db_data: